#!/bin/bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

alias al="cat ~/.aliases"
alias q="exit"
alias da="deactivate"
alias tm="tmux"
alias ll="ls -l"

# django
alias drs="python manage.py runserver"
alias dm="python manage.py migrate"
alias dsh="python manage.py shell"

# git
alias gpuom="git push -u origin master"
alias gpom="git push origin master"

# jekyll
alias jsl="jekyll serve --livereload"

# pip
alias pfr="pip freeze > requirements.txt"
alias pir="pip install -r requirements.txt"

# python
alias pve="python3 -m venv .env"
alias pve37="/usr/local/opt/python@3.7/bin/python3 -m venv .env"
alias pve38="/usr/local/opt/python@3.8/bin/python3 -m venv .env"
alias sea="source .env/bin/activate"
alias pup="python -m pip install --upgrade pip"
alias wp="which python"

# ruby
alias bcf="bundle clean --force"
