#!/bin/bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

alias al="cat ~/.aliases"

alias q="exit"
alias da="deactivate"
alias tm="tmux"
alias ll="ls -l"

# jekyll
alias jsl="jekyll serve --livereload"

# python
alias pup="python -m pip install --upgrade pip"

# pip
alias pfr="pip freeze > requirements.txt"
alias pir="pip install -r requirements.txt"

# git
alias gpuom="git push -u origin master"
alias gpom="git push origin master"

# django
alias drs="python manage.py runserver"
alias dm="python manage.py migrate"
